#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalBackEnd.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RentalHouse")]
	public partial class LandlordDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LandlordDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RentalHouseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LandlordDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandlordDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandlordDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LandlordDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spLandlordRegistration]")]
		public int _spLandlordRegistration([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(100)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="VarChar(100)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(MAX)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Image", DbType="VarChar(MAX)")] string image)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, password, email, number, address, image);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spAddProperty]")]
		public int _spAddProperty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyName", DbType="VarChar(100)")] string propertyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SqureFeet", DbType="VarChar(50)")] string squreFeet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentalCost", DbType="Decimal(18,0)")] System.Nullable<decimal> rentalCost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(MAX)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="VarChar(20)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LandLordname", DbType="VarChar(50)")] string landLordname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyImage", DbType="VarChar(MAX)")] string propertyImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentarId", DbType="Int")] System.Nullable<int> rentarId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyName, squreFeet, rentalCost, city, location, type, landLordname, propertyImage, rentarId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spPropertyResponse]")]
		public ISingleResult<_spPropertyResponseResult> _spPropertyResponse([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentarId", DbType="Int")] System.Nullable<int> rentarId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rentarId);
			return ((ISingleResult<_spPropertyResponseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spgetMyProperties]")]
		public ISingleResult<_spgetMyPropertiesResult> _spgetMyProperties([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentarId", DbType="Int")] System.Nullable<int> rentarId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rentarId);
			return ((ISingleResult<_spgetMyPropertiesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spDeletePropery]")]
		public int _spDeletePropery([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spGetPropertyById]")]
		public ISingleResult<_spGetPropertyByIdResult> _spGetPropertyById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId);
			return ((ISingleResult<_spGetPropertyByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spUpdateProperty]")]
		public int _spUpdateProperty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyName", DbType="VarChar(100)")] string propertyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SqureFeet", DbType="VarChar(50)")] string squreFeet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentalCost", DbType="Decimal(18,0)")] System.Nullable<decimal> rentalCost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(MAX)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="VarChar(20)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LandLordName", DbType="VarChar(50)")] string landLordName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyImage", DbType="VarChar(MAX)")] string propertyImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyName, squreFeet, rentalCost, city, location, type, landLordName, propertyImage, propertyId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spLandLordLogin]")]
		public ISingleResult<_spLandLordLoginResult> _spLandLordLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
			return ((ISingleResult<_spLandLordLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spBuyerTable]")]
		public int _spBuyerTable([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BuyerId", DbType="Int")] System.Nullable<int> buyerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SellerId", DbType="Int")] System.Nullable<int> sellerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LandLordName", DbType="VarChar(50)")] string landLordName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RentAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> rentAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecurityDeposit", DbType="Decimal(18,0)")] System.Nullable<decimal> securityDeposit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), buyerId, sellerId, propertyId, landLordName, rentAmount, securityDeposit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_spGetShowRequest]")]
		public ISingleResult<_spGetShowRequestResult> _spGetShowRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyId", DbType="Int")] System.Nullable<int> propertyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyId);
			return ((ISingleResult<_spGetShowRequestResult>)(result.ReturnValue));
		}
	}
	
	public partial class _spPropertyResponseResult
	{
		
		private int _PropertyId;
		
		private string _PropertyName;
		
		private string _SqureFeet;
		
		private System.Nullable<decimal> _RentalCost;
		
		private string _City;
		
		private string _Location;
		
		private string _Type;
		
		private string _LandLordName;
		
		private string _PropertyImage;
		
		private System.Nullable<int> _RentarId;
		
		public _spPropertyResponseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyId", DbType="Int NOT NULL")]
		public int PropertyId
		{
			get
			{
				return this._PropertyId;
			}
			set
			{
				if ((this._PropertyId != value))
				{
					this._PropertyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="VarChar(100)")]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqureFeet", DbType="VarChar(50)")]
		public string SqureFeet
		{
			get
			{
				return this._SqureFeet;
			}
			set
			{
				if ((this._SqureFeet != value))
				{
					this._SqureFeet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentalCost", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> RentalCost
		{
			get
			{
				return this._RentalCost;
			}
			set
			{
				if ((this._RentalCost != value))
				{
					this._RentalCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(MAX)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(20)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordName", DbType="VarChar(50)")]
		public string LandLordName
		{
			get
			{
				return this._LandLordName;
			}
			set
			{
				if ((this._LandLordName != value))
				{
					this._LandLordName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyImage", DbType="VarChar(MAX)")]
		public string PropertyImage
		{
			get
			{
				return this._PropertyImage;
			}
			set
			{
				if ((this._PropertyImage != value))
				{
					this._PropertyImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentarId", DbType="Int")]
		public System.Nullable<int> RentarId
		{
			get
			{
				return this._RentarId;
			}
			set
			{
				if ((this._RentarId != value))
				{
					this._RentarId = value;
				}
			}
		}
	}
	
	public partial class _spgetMyPropertiesResult
	{
		
		private int _PropertyId;
		
		private string _PropertyName;
		
		private string _SqureFeet;
		
		private System.Nullable<decimal> _RentalCost;
		
		private string _City;
		
		private string _Location;
		
		private string _Type;
		
		private string _LandLordName;
		
		private string _PropertyImage;
		
		private System.Nullable<int> _RentarId;
		
		public _spgetMyPropertiesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyId", DbType="Int NOT NULL")]
		public int PropertyId
		{
			get
			{
				return this._PropertyId;
			}
			set
			{
				if ((this._PropertyId != value))
				{
					this._PropertyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="VarChar(100)")]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqureFeet", DbType="VarChar(50)")]
		public string SqureFeet
		{
			get
			{
				return this._SqureFeet;
			}
			set
			{
				if ((this._SqureFeet != value))
				{
					this._SqureFeet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentalCost", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> RentalCost
		{
			get
			{
				return this._RentalCost;
			}
			set
			{
				if ((this._RentalCost != value))
				{
					this._RentalCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(MAX)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(20)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordName", DbType="VarChar(50)")]
		public string LandLordName
		{
			get
			{
				return this._LandLordName;
			}
			set
			{
				if ((this._LandLordName != value))
				{
					this._LandLordName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyImage", DbType="VarChar(MAX)")]
		public string PropertyImage
		{
			get
			{
				return this._PropertyImage;
			}
			set
			{
				if ((this._PropertyImage != value))
				{
					this._PropertyImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentarId", DbType="Int")]
		public System.Nullable<int> RentarId
		{
			get
			{
				return this._RentarId;
			}
			set
			{
				if ((this._RentarId != value))
				{
					this._RentarId = value;
				}
			}
		}
	}
	
	public partial class _spGetPropertyByIdResult
	{
		
		private int _PropertyId;
		
		private string _PropertyName;
		
		private string _SqureFeet;
		
		private System.Nullable<decimal> _RentalCost;
		
		private string _City;
		
		private string _Location;
		
		private string _Type;
		
		private string _LandLordName;
		
		private string _PropertyImage;
		
		private System.Nullable<int> _RentarId;
		
		public _spGetPropertyByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyId", DbType="Int NOT NULL")]
		public int PropertyId
		{
			get
			{
				return this._PropertyId;
			}
			set
			{
				if ((this._PropertyId != value))
				{
					this._PropertyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="VarChar(100)")]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SqureFeet", DbType="VarChar(50)")]
		public string SqureFeet
		{
			get
			{
				return this._SqureFeet;
			}
			set
			{
				if ((this._SqureFeet != value))
				{
					this._SqureFeet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentalCost", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> RentalCost
		{
			get
			{
				return this._RentalCost;
			}
			set
			{
				if ((this._RentalCost != value))
				{
					this._RentalCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(MAX)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(20)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandLordName", DbType="VarChar(50)")]
		public string LandLordName
		{
			get
			{
				return this._LandLordName;
			}
			set
			{
				if ((this._LandLordName != value))
				{
					this._LandLordName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyImage", DbType="VarChar(MAX)")]
		public string PropertyImage
		{
			get
			{
				return this._PropertyImage;
			}
			set
			{
				if ((this._PropertyImage != value))
				{
					this._PropertyImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentarId", DbType="Int")]
		public System.Nullable<int> RentarId
		{
			get
			{
				return this._RentarId;
			}
			set
			{
				if ((this._RentarId != value))
				{
					this._RentarId = value;
				}
			}
		}
	}
	
	public partial class _spLandLordLoginResult
	{
		
		private int _RentarId;
		
		private string _Email;
		
		private string _Password;
		
		private string _UserName;
		
		public _spLandLordLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentarId", DbType="Int NOT NULL")]
		public int RentarId
		{
			get
			{
				return this._RentarId;
			}
			set
			{
				if ((this._RentarId != value))
				{
					this._RentarId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
	}
	
	public partial class _spGetShowRequestResult
	{
		
		private System.Nullable<decimal> _RentAmount;
		
		private System.Nullable<decimal> _SecurityDeposit;
		
		private string _Username;
		
		private string _Email;
		
		private string _Number;
		
		private string _Address;
		
		private string _Image;
		
		public _spGetShowRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentAmount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> RentAmount
		{
			get
			{
				return this._RentAmount;
			}
			set
			{
				if ((this._RentAmount != value))
				{
					this._RentAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityDeposit", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SecurityDeposit
		{
			get
			{
				return this._SecurityDeposit;
			}
			set
			{
				if ((this._SecurityDeposit != value))
				{
					this._SecurityDeposit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this._Image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
